name: dbt Run
on: push
jobs:
  run-dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dbt
        run: pip install dbt-bigquery
      - name: Run dbt models
        run: dbt run
