name: dbt Run (PostgreSQL)

on:
  push:
    branches: [ main ]

jobs:
  run-dbt:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dbt (Postgres)
      run: pip install dbt-postgres

    # Dynamically create profiles.yml for PostgreSQL
    - name: Write dbt profile (PostgreSQL)
      run: |
        mkdir -p ~/.dbt
        echo "
        finance_project:
          target: dev
          outputs:
            dev:
              type: postgres
              host: localhost
              user: postgres
              password: '1234'
              port: 5432
              dbname: excel_db
              schema: finance
              threads: 4
        " > ~/.dbt/profiles.yml

    - name: Test dbt connection
      run: dbt debug
    
    - name: Run dbt models
      run: dbt run
