name: dbt Run (PostgreSQL - Localhost)

on:
  push:
    branches: [ main ]

jobs:
  run-dbt:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dbt and PostgreSQL Client
      run: |
        pip install dbt-postgres
        sudo apt-get install postgresql-client

    - name: Test PostgreSQL Connection
      run: |
        PGPASSWORD='1234' psql -h localhost -U postgres -d excel_db -p 5432 -c "\dt"

    - name: Write dbt profile (PostgreSQL)
      run: |
        mkdir -p ~/.dbt
        echo "
        finance_project:
          target: dev
          outputs:
            dev:
              type: postgres
              host: localhost
              user: postgres
              password: '1234'
              port: 5432
              dbname: excel_db
              schema: finance
              threads: 4
        " > ~/.dbt/profiles.yml

    - name: Print profiles.yml (for Debugging)
      run: cat ~/.dbt/profiles.yml

    - name: Create Schema if Missing
      run: |
        PGPASSWORD='1234' psql -h localhost -U postgres -d excel_db -p 5432 -c "CREATE SCHEMA IF NOT EXISTS finance"

    - name: Test dbt connection
      run: dbt debug
    
    - name: Run dbt models
      run: dbt run
