name: Run dbt Models on Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt_run:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13  # Use the PostgreSQL Docker image
        ports:
          - 5432:5432  # Expose PostgreSQL port
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: '1234'
          POSTGRES_DB: excel_db
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dbt and Dependencies
        run: |
          pip install --upgrade pip
          pip install dbt-postgres

      - name: Set up PostgreSQL Database Credentials
        env:
          DB_HOST: localhost  # Use localhost since the database is within the container
          DB_USER: postgres
          DB_PASSWORD: '1234'
          DB_NAME: excel_db
        run: |
          echo "Setting up PostgreSQL credentials..."
          echo "DB_HOST=${DB_HOST}" >> $GITHUB_ENV
          echo "DB_USER=${DB_USER}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${DB_PASSWORD}" >> $GITHUB_ENV
          echo "DB_NAME=${DB_NAME}" >> $GITHUB_ENV

      - name: Create dbt profiles.yml for PostgreSQL
        run: |
          mkdir -p ~/.dbt
          echo "finance_project:
            target: dev
            outputs:
              dev:
                type: postgres
                host: ${DB_HOST}
                user: ${DB_USER}
                password: \"${DB_PASSWORD}\"
                port: 5432
                dbname: ${DB_NAME}
                schema: finance
                threads: 4" > ~/.dbt/profiles.yml

      - name: Run dbt
        run: |
          echo "Running dbt models..."
          dbt run
