name: Run dbt Models on Push

on:
  push:
    branches:
      - main  # You can adjust this to trigger for other branches as needed
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  dbt_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Check out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use Python version 3.x

      - name: Install dbt and Dependencies
        run: |
          pip install --upgrade pip
          pip install dbt-postgres  # Install dbt for PostgreSQL

      - name: Set up PostgreSQL Database Credentials
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: '1234'  # Ensure the password is a string (with quotes)
          DB_NAME: excel_db
        run: |
          echo "Setting up PostgreSQL credentials..."
          echo "DB_HOST=${DB_HOST}" >> $GITHUB_ENV
          echo "DB_USER=${DB_USER}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${DB_PASSWORD}" >> $GITHUB_ENV
          echo "DB_NAME=${DB_NAME}" >> $GITHUB_ENV

      - name: Create dbt profiles.yml for PostgreSQL
        run: |
          mkdir -p ~/.dbt
          echo "finance_project:
            target: dev
            outputs:
              dev:
                type: postgres
                host: ${DB_HOST}
                user: ${DB_USER}
                password: \"${DB_PASSWORD}\"  # Ensure password is treated as a string
                port: 5432
                dbname: ${DB_NAME}
                schema: finance
                threads: 4" > ~/.dbt/profiles.yml

      - name: Run dbt
        run: |
          echo "Running dbt models..."
          dbt run  # Run the dbt models
